{"name": "test_01_custom_login[18500228275-111111-登录成功]", "status": "broken", "statusDetails": {"message": "TypeError: '../test_result/report/allure_report' is not a valid filepath", "trace": "self = <allure_commons._allure.fixture object at 0x10cc736a0>, args = (), kwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n../../../appium/venv/lib/python3.8/site-packages/allure_commons/_allure.py:185: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../conftest.py:38: in end\n    send_mail(\"../test_result/report/allure_report\")\n../conftest.py:80: in send_mail\n    yag.send([\"hehuaimei@dangdang.com\",\"hehuaimei123@163.com\"],subject,contents,attachment)\n../../../appium/venv/lib/python3.8/site-packages/yagmail/sender.py:148: in send\n    recipients, msg_string = self.prepare_send(\n../../../appium/venv/lib/python3.8/site-packages/yagmail/sender.py:118: in prepare_send\n    msg = prepare_message(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nuser = 'hehuaimei123@163.com', useralias = 'hehuaimei123@163.com'\naddresses = {'To': 'hehuaimei@dangdang.com; hehuaimei123@163.com', 'recipients': ['hehuaimei@dangdang.com', 'hehuaimei123@163.com']}, subject = '自动化测试报告'\ncontents = ['python自动化测试报告，自动发送。'], attachments = ['../test_result/report/allure_report'], headers = None, encoding = 'utf-8', newline_to_break = True\n\n    def prepare_message(user, useralias, addresses, subject, contents, attachments, headers, encoding, newline_to_break=True):\n        # check if closed!!!!!! XXX\n        \"\"\" Prepare a MIME message \"\"\"\n        if isinstance(contents, text_type):\n            contents = [contents]\n        if isinstance(attachments, text_type):\n            attachments = [attachments]\n    \n        # merge contents and attachments for now.\n        if attachments is not None:\n            for a in attachments:\n                if not os.path.isfile(a):\n>                   raise TypeError(\"'{0}' is not a valid filepath\".format(a))\nE                   TypeError: '../test_result/report/allure_report' is not a valid filepath\n\n../../../appium/venv/lib/python3.8/site-packages/yagmail/message.py:27: TypeError"}, "attachments": [{"name": "log", "source": "95a38410-1b8a-455d-b90c-83813e70a943-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "account", "value": "'18500228275'"}, {"name": "pw", "value": "'111111'"}, {"name": "toast", "value": "'登录成功'"}], "start": 1587642321272, "stop": 1587642357875, "uuid": "f9c41366-4486-411f-bbcc-a26086988293", "historyId": "900ee40f296262deb0da16d4eb0bdcd1", "testCaseId": "5c27a854897a1d9e4acd58f324d6d476", "fullName": "test_case.test_01_login.TestLogin#test_01_custom_login", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_01_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "bogon"}, {"name": "thread", "value": "22738-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_01_login"}]}